steps:
  # SSH into the instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-latest', '--zone=us-central1-a', '--command', 'sudo mkdir /var/test']

  # Confirm directory creation
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-latest', '--zone=us-central1-a', '--command', 'ls -l /var']
